project:
  type: book
  pre-render: scripts/build_presentations.R # write this in same line
execute:
  freeze: auto
  cache: true
book:
  title: "MCQs from Shackelford's Surgery"
  reader-mode: true 
  author: "Dr Suman Khanal"
  date: 2026/02/01
  date-format: iso 
  search: true
  sharing: [twitter, facebook]
  sidebar:
    style: docked
    background: light
  
  
  # Multi-volume structure
  chapters:
    - index.qmd
    - part: "VOLUME 1"
    - chapters/1_Anatomy_of_the_Esophagus_and_the_Gastroesophageal_Reflux_Barrier.qmd
    - chapters/2_Esophageal_Motility_Techniques_Used_for_the_Diagnosis_of_Esophageal_Motility_Disorders_and_for_Surgical_Decision_Making.qmd
    - chapters/3_Endoscopic_Evaluation_of_the_Esophagus_Key_Components_for_Surgeons.qmd
    - chapters/4_pH_and_Impedance_Evaluation_of_the_Esophagus.qmd
    - chapters/5_Radiology_of_the_Esophagus_Barium_Computed_Tomography_Scan_Positron_Emission_Tomography_Scan_Magnetic_Resonance_Imaging.qmd
    - chapters/6_Esophageal_Symptoms_and_Selection_of_Diagnostic_Tests.qmd
    - chapters/7_Pathophysiology_of_Gastroesophageal_Reflux.qmd
    - chapters/8_Acid-Suppression_Therapy_for_Gastroesophageal_Reflux_Disease_and_the_Therapeutic_Gap.qmd
    - chapters/9_Fundoplication_for_Gastroesophageal_Reflux_Disease.qmd
    - chapters/10_Magnetic_Sphincter_Augmentation_for_Gastroesophageal_Reflux_Disease.qmd
    - chapters/11_Endoscopic_Approach_to_Gastroesophageal_Reflux_Disease.qmd
    - chapters/12_Delayed_Gastric_Emptying_in_Gastroesophageal_Reflux_Disease.qmd
    - chapters/13_Patient_Selection_for_Antireflux_Surgery.qmd
    - chapters/14_Management_of_Gastroesophageal_Reflux_Disease_With_Esophageal_Dysmotility_Scleroderma_and_End-Stage_Reflux.qmd
    - chapters/15_The_Role_of_Gastroesophageal_Reflux_Disease_in_Pulmonary_Disease.qmd
    - chapters/16_Management_of_Failed_Antireflux_Procedures.qmd
    - chapters/17_Obesity_and_GERD.qmd
    - chapters/18_Cricopharyngeal_Dysfunction_and_Zenker_Diverticulum.qmd
    - chapters/19_Achalasia_Diagnosis_and_Treatment.qmd
    - chapters/20_Surgical_Management_of_Mid-_and_Distal_Esophageal_Diverticula.qmd
    - chapters/21_Paraesophageal_Hernia_Etiology_Presentation_and_Indications_for_Repair.qmd
    - chapters/22_Laparoscopic_Paraesophageal_Hernia_Repair_Key_Components_of_Repair.qmd
    - chapters/23_Mesh_at_the_Hiatus.qmd
    - chapters/24_Reducing_Tension_Diaphragmatic_Relaxing_Incisions_and_Esophageal_Lengthening_During_Large_Hiatal_Hernia_Repair.qmd
    - chapters/25_Controversies_in_the_Definition_of_Barrett’s_Esophagus.qmd
    - chapters/26_Management_of_Barrett’s_Esophagus.qmd
    - chapters/27_Medical_and_Surgical_Therapy_for_Gastroesophageal_Reflux_Disease_and_Barrett’s_Esophagus.qmd
    - chapters/28_Epidemiology_Risk_Factors_and_Clinical_Manifestations_of_Esophageal_Cancer.qmd
    - chapters/29_Endoscopic_Management_of_High-Grade_Dysplasia_and_Superficial_Esophageal_Carcinoma.qmd
    - chapters/30_Endoscopic_Ultrasound_of_the_Esophagus.qmd
    - chapters/31_Esophageal_Cancer_Diagnosis_and_Staging.qmd
    - chapters/32_Neoadjuvant_Treatments_in_Locally_Advanced_Esophageal_Cancer.qmd
    - chapters/33_Esophagectomy_Techniques.qmd
    - chapters/34_Extent_of_Lymphadenectomy_for_Esophageal_Cancer.qmd
    - chapters/35_Options_for_Esophageal_Replacement.qmd
    - chapters/36_Anastomotic_Complications_After_Esophagectomy.qmd
    - chapters/37_Survivorship_Pathways_in_Esophagectomy_Prehabilitation_Enhanced_Recovery_and_Rehabilitation.qmd
    - chapters/38_Palliative_Therapy_for_Esophageal_Cancer.qmd
    - chapters/39_Management_of_Esophageal_Perforation.qmd
    - chapters/40_Submucosal_Tumors_in_the_Esophagus_and_Gastroesophageal_Junction.qmd
    - chapters/41_Esophageal_Duplication_Cyst.qmd
    - chapters/42_Caustic_Esophageal_Injury.qmd
    - chapters/44_Mesh_Material_Science_of_Hernia_Repair.qmd
    - chapters/45_Primary_Umbilical_and_Epigastric_Hernias_Open_and_MIS_Approaches.qmd
    - chapters/46_Ventral_Hernia—MIS_Approaches.qmd
    - chapters/47_Open_Ventral_Hernia_Repair_Management_of_Contamination_and_Open_Abdomens.qmd
    - chapters/48_Parastomal_Hernia—MIS_Approaches.qmd
    - chapters/49_Open_Approaches_to_Parastomal_Hernia_Repair.qmd
    - chapters/50_Inguinal_Hernia_Repair—Minimally_Invasive_Approaches.qmd
    - chapters/51_Inguinal_Femoral_Hernia_Repair_Open_Tissue-Based_Approaches.qmd
    - chapters/52_Inguinal_Hernia_Repair—Open_Repair_With_Mesh.qmd
    - chapters/53_Uncommon_Hernias.qmd
    - chapters/54_Gastric_Volvulus.qmd
    - chapters/55_Anatomy_and_Physiology_of_the_Stomach.qmd
    - chapters/56_Diagnostic_and_Therapeutic_Endoscopy_of_the_Stomach_and_Small_Bowel.qmd
    - chapters/57_Invasive_and_Noninvasive_Access_of_the_Stomach_and_Small_Intestine.qmd
    - chapters/58_Surgery_for_Peptic_Ulcer_Disease.qmd
    - chapters/59_Gastric_Adenocarcinoma_Including_Landmark_Clinical_Trials.qmd
    - chapters/60_Endoscopic_Management_of_Early_Gastric_Cancers.qmd
    - chapters/61_Postgastrectomy_Syndromes.qmd
    - chapters/62_Foreign_Bodies_and_Bezoars_of_the_Stomach_and_Small_Intestine.qmd
    - chapters/63_Motility_Disorders_of_the_Stomach_and_Small_Intestine.qmd
    - chapters/64_Miscellaneous_Benign_Lesions_and_Conditions_of_the_Stomach_Duodenum_and_Small_Intestine.qmd
    - chapters/65_Surgical_Disease_of_the_Stomach_and_Duodenum_in_Infants_and_Children.qmd
    - chapters/66_The_Obesity_Pandemic.qmd
    - chapters/67_Medical_Management_of_Obesity.qmd
    - chapters/68_Endoscopic_Management_of_Morbid_Obesity.qmd
    - chapters/69_Operations_for_Morbid_Obesity.qmd
    - chapters/70_Management_of_Complications_of_Bariatric_Surgery.qmd
    - chapters/71_Anatomy_and_Physiology_of_the_Duodenum.qmd
    - chapters/72_Adenocarcinoma_of_the_Small_Intestine.qmd
    - chapters/73_Reoperations_on_the_Stomach_and_Duodenum.qmd
    - chapters/74_Small_Intestine.qmd
    - chapters/75_Small_Bowel_Obstruction.qmd
    - chapters/76_Internal_Hernias_Congenital_and_Acquired.qmd
    - chapters/77_Gastric_Duodenal_and_Small_Intestinal_Fistulas.qmd
    - chapters/78_Small_Bowel_Diverticula.qmd
    - chapters/79_Radiation_Enteritis.qmd
    - chapters/80_Short_Bowel_Syndrome.qmd
    - chapters/81_Gastrointestinal_Neuroendocrine_Tumors.qmd
    - chapters/82_Gastrointestinal_Stromal_Tumors.qmd
    - chapters/83_Gastrointestinal_Lymphomas.qmd
    - chapters/84_Surgical_Conditions_of_the_Small_Intestine_in_Infants_and_Children.qmd
    - chapters/85_Ileostomy.qmd
    - chapters/86_Suturing_Stapling_and_Tissue_Adhesion.qmd
    - chapters/87_Anatomy_and_Physiology_of_the_Mesenteric_Circulation.qmd
    - chapters/88_Mesenteric_Ischemia.qmd
    - chapters/89_The_Current_Management_of_Aortoenteric_Fistula_and_Visceral_Artery_Aneurysms.qmd
    - chapters/90_Visceral_Arterial_Trauma.qmd
    - part: "VOLUME 2"
    - chapters/91_Anatomy_Physiology_and_Embryology_of_the_Pancreas.qmd
    - chapters/92_Genetic_Syndromes_Associated_With_Pancreatic_Disease.qmd
    - chapters/93_Acute_Pancreatitis.qmd
    - chapters/94_Chronic_Pancreatitis.qmd
    - chapters/95_Pseudocysts_and_Other_Complications_of_Pancreatitis.qmd
    - chapters/96_Endoscopic_and_Minimally_Invasive_Therapy_for_Complications_of_Pancreatitis.qmd
    - chapters/97_Imaging_of_and_Radiologic_Intervention_in_the_Pancreas.qmd
    - chapters/98_Pancreatic_Cancer.qmd
    - chapters/99_Periampullary_Tumors.qmd
    - chapters/100_Pancreatic_Neuroendocrine_Neoplasms.qmd
    - chapters/101_Zollinger-Ellison_Syndrome.qmd
    - chapters/102_Primary_Pancreatic_Cystic_Neoplasms.qmd
    - chapters/103_Unusual_Pancreatic_Tumors.qmd
    - chapters/104_Techniques_of_Pancreatic_Resection_for_Cancer.qmd
    - chapters/105_Minimally_Invasive_Pancreas_Surgery.qmd
    - chapters/106_Prevention_and_Management_of_Complications_of_Pancreatic_Surgery.qmd
    - chapters/107_Landmark_Trials_for_Pancreatic_Cancer.qmd
    - chapters/108_Endoscopic_Interventions_for_Pancreatic_Malignancies.qmd
    - chapters/109_Pancreatic_Trauma.qmd
    - chapters/110_Pancreatic_Problems_in_Infants_and_Children.qmd
    - chapters/111_Total_Pancreatectomy_With_Islet_Autotransplantation.qmd
    - chapters/112_Embryology_Anatomy_and_Physiology_of_the_Biliary_Tract.qmd
    - chapters/113_Imaging_and_Radiologic_Intervention_in_the_Biliary_Tract.qmd
    - chapters/114_Endoscopic_Evaluation_and_Management_of_Biliary_Disease.qmd
    - chapters/115_Management_of_Cholecystitis_and_Cholelithiasis.qmd
    - chapters/116_Management_of_Common_Bile_Duct_Stones.qmd
    - chapters/117_Biliary_Dyskinesia_and_Sphincter_of_Oddi_Dysfunction.qmd
    - chapters/118_Management_of_Gallbladder_Cancer_and_Premalignant_Gallbladder_Lesions.qmd
    - chapters/119_Biliary_Tract_Tumors.qmd
    - chapters/120_Prevention_and_Management_of_Iatrogenic_Bile_Duct_Injury.qmd
    - chapters/121_Operative_Management_of_Biliary_Stricture.qmd
    - chapters/122_Cystic_Disorders_of_the_Bile_Ducts.qmd
    - chapters/123_Surgical_Treatment_of_Primary_Sclerosing_Cholangitis.qmd
    - chapters/124_Recurrent_Pyogenic_Cholangitis_and_Intrahepatic_Stone_Diseases.qmd
    - chapters/125_Biliary_Parasitic_Disease.qmd
    - chapters/126_Anatomy_Physiology_and_Embryology_of_the_Liver.qmd
    - chapters/127_Liver_Imaging.qmd
    - chapters/128_Assessment_of_Hepatic_Function_and_Preoperative_Hepatic_Optimization.qmd
    - chapters/129_Perioperative_Management_and_Nutritional_Support_in_Patients_With_Liver_and_Biliary_Tract_Disease.qmd
    - chapters/130_Hepatic_Cysts.qmd
    - chapters/131_Infections_of_the_Liver.qmd
    - chapters/132_Management_of_Hepatobiliary_Injury.qmd
    - chapters/133_Operative_Techniques_and_Principles_of_Hepatic_Resection.qmd
    - chapters/134_Minimally_Invasive_Techniques_of_Hepatic_Resection.qmd
    - chapters/135_Management_of_Colorectal_Liver_Metastases.qmd
    - chapters/136_Ablative_Therapies_for_Hepatic_Neoplasms.qmd
    - chapters/137_Liver_Transplantation.qmd
    - chapters/138_Transplant_Oncology.qmd
    - chapters/139_Intraarterial_Therapy_and_Hepatic_Artery_Infusion_Chemotherapy.qmd
    - chapters/140_Liver_Failure_and_Bioartificial_Liver_Support.qmd
    - chapters/141_Vascular_Diseases_of_the_Liver.qmd
    - chapters/142_Medical_Diseases_of_the_Liver_for_the_Surgeon.qmd
    - chapters/143_Benign_Hepatic_Neoplasms.qmd
    - chapters/144_Management_of_Hepatocellular_Carcinoma.qmd
    - chapters/145_Management_of_Primary_Malignant_Hepatic_Neoplasms_Other_Than_Hepatocellular_Cancer.qmd
    - chapters/146_Management_of_Noncolorectal_Liver_Metastases.qmd
    - chapters/147_Management_of_Portal_Hypertension.qmd
    - chapters/148_Radiotherapy_for_Liver_Tumors.qmd
    - chapters/149_Nonhepatic_Surgery_in_Patients_With_Cirrhosis.qmd
    - chapters/150_Anatomy_and_Physiology_of_the_Spleen.qmd
    - chapters/151_Splenectomy_for_Conditions_Other_Than_Trauma.qmd
    - chapters/152_Minimally_Invasive_Surgical_and_Image-Guided_Interventional_Approaches_to_the_Spleen.qmd
    - chapters/153_Management_of_Splenic_Trauma_in_Adults_and_Children.qmd
    - chapters/154_Management_of_Incidentally_Found_Adrenal_Masses.qmd
    - chapters/155_Open_and_Minimally_Invasive_Approaches_to_Adrenal_Tumors.qmd
    - chapters/157_Operative_Anatomy_of_the_Colon_Rectum_and_Anus.qmd
    - chapters/158_Colonic_Motility_Anorectal_Physiology_Pelvic_Floor_Anatomy_and_Function.qmd
    - chapters/159_Advanced_Endoscopic_Imaging_and_Therapeutic_Interventions.qmd
    - chapters/160_Magnetic_Resonance_Imaging_of_Rectal_Cancer.qmd
    - chapters/161_Diagnosis_and_Management_of_Fecal_Incontinence.qmd
    - chapters/162_Low_Anterior_Resection_Syndrome_and_Colonic_Dysmotility.qmd
    - chapters/163_Obstructed_Defecation_Syndrome_and_Pelvic_Floor_Dysfunction.qmd
    - chapters/164_Rectovaginal_and_Rectourethral_Fistulas.qmd
    - chapters/165_Rectal_Prolapse_External_Rectal_Prolapse_and_Internal_Intussusception.qmd
    - chapters/166_Pilonidal_Disease_and_Perianal_Hidradenitis.qmd
    - chapters/167_Emergent_Care_of_the_Victim_of_Colorectal_Trauma.qmd
    - chapters/168_Colonic_Intussusception_and_Volvulus.qmd
    - chapters/169_Lower_Gastrointestinal_Bleeding.qmd
    - chapters/170_Acute_Diverticulitis.qmd
    - chapters/171_Rectal_Pain_and_Bleeding_Hemorrhoids_and_Anal_Fissures.qmd
    - chapters/172_Perirectal_Abscess_and_Fistula-in-Ano.qmd
    - chapters/173_Infectious_Colitis_and_Proctitis.qmd
    - chapters/174_Concepts_in_Inflammatory_Bowel_Disease_Management.qmd
    - chapters/175_Operative_Therapy_for_Ulcerative_Colitis_A_Minimally_Invasive_Approach.qmd
    - chapters/176_Surgery_for_Crohn’s_Disease.qmd
    - chapters/177_Appendix.qmd
    - chapters/178_Inherited_Colorectal_Cancer_and_the_Genetics_of_Colorectal_Cancer.qmd
    - chapters/179_Transanal_Approaches_to_Early_Rectal_Cancer.qmd
    - chapters/180_Sphincter-Preserving_TME_for_Rectal_Cancer_Open_Laparoscopic_Robotic_and_Transanal_TME.qmd
    - chapters/181_Abdominoperineal_Resection_for_Rectal_Cancer.qmd
    - chapters/182_Minimally_Invasive_Approaches_to_Colon_Cancer.qmd
    - chapters/183_Principles_of_Management_of_Recurrent_and_Metastatic_Colorectal_Cancer.qmd
    - chapters/184_Anal_Dysplasia_and_Anal_Cancers.qmd
    - chapters/185_Retrorectal_Tumors.qmd
    - chapters/186_Rare_Colorectal_Malignancies.qmd
    - chapters/187_Adjuvant_and_Neoadjuvant_Therapy_for_Colorectal_Cancer_Molecular-Based_Therapy_Including_Landmark_Trials.qmd
    - chapters/188_HIPEC_for_Appendiceal_and_Colorectal_Cancers.qmd
    - chapters/189_Anastomotic_Leaks.qmd
    - chapters/190_Ostomy_Construction_and_Management_Personalizing_the_Stoma_for_the_Patient.qmd
    - chapters/191_Reducing_the_Risk_of_Infection_in_the_Elective_and_Emergent_Colectomy_Patient.qmd
    - chapters/192_Reoperative_Pelvic_Surgery.qmd
    - chapters/193_Enhanced_Recovery_Protocols_in_Colorectal_Surgery.qmd
    - chapters/194_Colorectal_Surgery_in_Patients_With_Obesity.qmd
    - chapters/195_Delivering_High-Quality_and_Equitable_Surgical_Care_Quality_Metrics_Improvement_and_Implementation.qmd
    - chapters/196_Management_of_Intraabdominal_and_Retroperitoneal_Sarcomas.qmd
    - part: "MISCELLANEOUS"


format:
  html:
    theme: 
      - cosmo
      - styles.scss
    css: styles.css
    # cover-image: cover.png
    title-block-banner: true
    code-fold: true
    code-summary: "Show code"
    toc: true
    toc-depth: 2
    number-sections: false
    number-depth: 3
    crossref:
      chapters: true
      fig-title: "Figure"
      tbl-title: "Table"
    
  pdf:
    documentclass: book
    classoption: [oneside, openany]
    geometry:
      - top=1in
      - bottom=1in
      - left=1.25in
      - right=1in
    fontsize: 11pt
    linestretch: 1.2
    toc: true
    toc-depth: 2
    number-sections: false
    colorlinks: true

